language: java
jdk: oraclejdk8
script:
  - mvn clean verify
  - mvn clean verify -P memory -DargLine="-Dspring.profiles.active=memory"
notifications:
  email:
    recipients:
      - kh.mv@bk.ru
    on_success: never
    on_failure: always