version: "2"

services:

  tomcat:
    image: glaizier/todo
    depends_on:
      - postgres
    # make tomcat wait for postgres to initialize
    # entrypoint overrides cmd in Dockerfile https://github.com/docker/compose/issues/3140
    # https://github.com/docker/compose/pull/3764 https://github.com/docker/docker/pull/25012
    # entrypoint: /bin/wait-for-it.sh postgres:5432 -- /usr/local/tomcat/bin/catalina.sh run
    command: ["/usr/local/scripts/wait-for-it.sh", "postgres:5432", "--", "/usr/local/tomcat/bin/catalina.sh", "run"]
    ports:
      - "8080:8080"
      - "8443:8443"

  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d